import os
import json
import time
import logging
import datetime
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

from db.db import get_db_connection
from config_loader import load_exclusions

logger = logging.getLogger("linkedin-agent.capture.file")

PROJECT_ROOT = Path(__file__).parent.parent.resolve()

class FileWatcherHandler(FileSystemEventHandler):
    """
    Handles filesystem events generated by watchdog, normalises file paths,
    applies exclusions, debounces rapid successive events, and logs them to the database.
    """
    def __init__(self, debounce_seconds: float = 5.0):
        super().__init__()
        self.debounce_seconds = debounce_seconds
        # Stores {(file_path, action): last_logged_timestamp}
        self.last_logged = {}
        
    def _is_excluded(self, file_path: Path) -> bool:
        resolved_path = Path(os.path.abspath(file_path))
        
        # 1. Load config exclusions
        exclusions = load_exclusions()
        
        # 2. Check excluded folders from exclusions.yaml
        for folder in exclusions.get("folders", []):
            try:
                expanded = Path(os.path.abspath(os.path.expanduser(folder)))
                if resolved_path.is_relative_to(expanded) or resolved_path == expanded:
                    return True
            except Exception as e:
                logger.warning(f"Error checking folder exclusion '{folder}': {e}")
                
        # 3. Always exclude built-in directories and files we don't want to track
        parts = resolved_path.parts
        ignored_dirs = {
            ".git", ".venv", "venv", "__pycache__", ".pytest_cache", "tests", "scratch",
            "node_modules", "dist", "build", ".idea", ".vscode", "agent_echo.egg-info"
        }
        for p in parts:
            if p in ignored_dirs or (p.startswith(".") and p != "."):
                return True
                
        # 4. Exclude temp files, databases, lockfiles, etc.
        suffix = resolved_path.suffix.lower()
        if suffix in (".pyc", ".pyo", ".pyd", ".db", ".db-journal", ".db-wal", ".db-shm", ".sqlite", ".log", ".lock", ".swp", ".tmp"):
            return True
            
        # 5. Do not track files inside data directory (screenshots, media) since the agent writes there
        if resolved_path.is_relative_to(PROJECT_ROOT / "data"):
            return True
            
        return False

    def _log_event(self, path_str: str, action: str):
        path = Path(os.path.abspath(path_str))
        if self._is_excluded(path):
            return
            
        try:
            rel_path = path.relative_to(PROJECT_ROOT)
        except ValueError:
            rel_path = path
            
        rel_path_str = str(rel_path)
        
        # Apply in-memory debounce to reduce noise (e.g. editor saving multiples)
        now = time.time()
        key = (rel_path_str, action)
        last_time = self.last_logged.get(key, 0.0)
        if now - last_time < self.debounce_seconds:
            return
            
        self.last_logged[key] = now
        
        logger.info(f"File event detected: {action} - {rel_path_str}")
        
        # Insert event into database
        conn = get_db_connection()
        cursor = conn.cursor()
        
        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()
        title = f"file {action}: {rel_path_str}"
        detail = {
            "project": "agent-echo",
            "file_path": rel_path_str,
            "action": action
        }
        
        try:
            cursor.execute(
                "INSERT INTO activity_events (source, event_time, title, detail) VALUES ('file', ?, ?, ?)",
                (now_iso, title, json.dumps(detail))
            )
            conn.commit()
        except Exception as e:
            logger.error(f"Failed to log file event to DB: {e}")
        finally:
            conn.close()

    def on_modified(self, event):
        if not event.is_directory:
            self._log_event(event.src_path, "edited")

    def on_created(self, event):
        if not event.is_directory:
            self._log_event(event.src_path, "created")

    def on_deleted(self, event):
        if not event.is_directory:
            self._log_event(event.src_path, "deleted")

def start_file_watcher(watch_path: str | None = None) -> Observer:
    """
    Initializes and starts the background watchdog file observer.
    """
    if not watch_path:
        watch_path = str(PROJECT_ROOT)
        
    logger.info(f"Starting file watcher for directory: {watch_path}")
    
    event_handler = FileWatcherHandler()
    observer = Observer()
    observer.schedule(event_handler, path=watch_path, recursive=True)
    observer.start()
    return observer

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger.info("Running file watcher standalone. Press Ctrl+C to exit.")
    obs = start_file_watcher()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        obs.stop()
    obs.join()
